# Generated by Django 4.1.2 on 2023-09-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_wishlistitem_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
